//! # zkProof — Zero-Knowledge Financial Attestation Verifier
//!
//! This Soroban contract verifies UltraHonk proofs generated by a Noir circuit
//! (compiled to Barretenberg v0.87.0 format) and issues on-chain attestations
//! that third parties can query.
//!
//! ## Flow
//! 1. User generates an UltraHonk proof in the browser via bb.js
//! 2. User calls `attest()` with the public inputs and the proof bytes
//! 3. Contract verifies the proof using the deployed Nethermind
//!    `ultrahonk_soroban_verifier` crate, which performs the full
//!    Oink + Sumcheck + Shplonk (BN254 pairing check) flow
//! 4. If valid, the contract stores an attestation on-chain
//! 5. Verifiers call `check()` to query attestations — get YES/NO only
//!
//! ## Key design decisions
//! - NO financial data ever touches the chain
//! - Attestations expire after 90 days (configurable)
//! - Users can revoke their own attestations
//! - Attestations are keyed by (address, attestation_type)
//! - The circuit's VK is uploaded once at deploy time via the constructor
//! - This contract is purpose-built for the income/balance/credit circuit in
//!   `circuits/src/main.nr` — the public input schema is enforced
#![no_std]

use soroban_sdk::{
    contract, contractimpl, contracttype,
    log, symbol_short, Address, Bytes, BytesN, Env, Symbol,
};
use ultrahonk_soroban_verifier::UltraHonkVerifier;

const PUBLIC_INPUT_BYTES: u32 = 32 * 4;
const PROOF_BYTES: u32 = 14592;

// ============================================================
// Data Types
// ============================================================

/// Represents an on-chain attestation credential
#[contracttype]
#[derive(Clone, Debug)]
pub struct Attestation {
    /// The Stellar address that holds this attestation
    pub holder: Address,
    /// Type of attestation: "income", "balance", "credit"
    pub attestation_type: Symbol,
    /// The threshold that was proven (e.g., 3000 for "$3,000/month")
    pub threshold: i128,
    /// Unix timestamp when the attestation was issued
    pub issued_at: u64,
    /// Unix timestamp when the attestation expires (default: 90 days)
    pub expires_at: u64,
    /// SHA256 hash of the proof for audit trail
    pub proof_hash: BytesN<32>,
}

/// Storage key for attestations: (holder_address, attestation_type)
#[contracttype]
#[derive(Clone)]
pub struct AttestationKey {
    pub holder: Address,
    pub att_type: Symbol,
}

/// Storage key for contract admin
#[contracttype]
#[derive(Clone)]
enum DataKey {
    Admin,
    /// Total number of attestations issued (for stats)
    TotalAttestations,
    /// Verification key for ZK proof verification (fixed 1760 raw bytes)
    VerificationKey,
}

// ============================================================
// Contract
// ============================================================

#[contract]
pub struct ZkProofVerifier;

#[contractimpl]
impl ZkProofVerifier {
    // --------------------------------------------------------
    // INITIALIZATION
    // --------------------------------------------------------

    /// Constructor — initializes the contract with an admin and uploads the
    /// circuit's verification key. Called once at deploy time.
    pub fn __constructor(env: Env, admin: Address, vk: Bytes) {
        if UltraHonkVerifier::new(&env, &vk).is_err() {
            panic!("Invalid verification key");
        }
        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::TotalAttestations, &0u64);
        env.storage().instance().set(&DataKey::VerificationKey, &vk);
        log!(&env, "zkProof contract initialized with VK");
    }

    /// Returns the stored VK. Useful for debugging or for the deploy script to
    /// verify the upload was correct.
    pub fn get_verification_key(env: Env) -> Option<Bytes> {
        env.storage().instance().get(&DataKey::VerificationKey)
    }

    /// Re-uploads the VK. Admin-only. Useful for circuit upgrades.
    pub fn store_verification_key(env: Env, admin: Address, vk: Bytes) {
        admin.require_auth();
        let stored_admin: Address = env
            .storage()
            .instance()
            .get(&DataKey::Admin)
            .unwrap_or_else(|| panic!("Contract not initialized"));
        if stored_admin != admin {
            panic!("Only admin can store verification key");
        }
        if UltraHonkVerifier::new(&env, &vk).is_err() {
            panic!("Invalid verification key");
        }
        env.storage().instance().set(&DataKey::VerificationKey, &vk);
        log!(&env, "Verification key stored");
    }

    // --------------------------------------------------------
    // CORE: Submit proof and receive attestation
    // --------------------------------------------------------

    /// Submit a ZK proof to receive an on-chain attestation.
    ///
    /// # Arguments
    /// * `user` - The address claiming the attestation
    /// * `public_inputs` - Exactly 4 × 32-byte Field elements
    ///     [0] minimum_threshold (u64 BE in the low 8 bytes)
    ///     [1] attestation_type (1=income, 2=balance, 3=credit)
    ///     [2] timestamp (u64 BE; must be > Jan 1 2024)
    ///     [3] data_commitment (Poseidon BN254 hash)
    /// * `proof` - The 14,592-byte UltraHonk proof produced by bb.js
    /// * `attestation_type` - Symbol: "income", "balance", or "credit"
    /// * `threshold` - The minimum threshold proven (e.g., 3000)
    ///
    /// # Returns
    /// * `true` if proof is valid and attestation was issued
    pub fn attest(
        env: Env,
        user: Address,
        public_inputs: Bytes,
        proof: Bytes,
        attestation_type: Symbol,
        threshold: i128,
    ) -> bool {
        // User must authorize this transaction
        user.require_auth();

        // ---- INPUT VALIDATION ----
        if public_inputs.len() != PUBLIC_INPUT_BYTES {
            log!(&env, "public_inputs wrong length");
            return false;
        }
        if proof.len() != PROOF_BYTES {
            log!(&env, "proof wrong length");
            return false;
        }
        if threshold < 0 {
            log!(&env, "threshold negative");
            return false;
        }

        // ---- ZK PROOF VERIFICATION ----
        let vk: Bytes = match env.storage().instance().get(&DataKey::VerificationKey) {
            Some(vk) => vk,
            None => {
                log!(&env, "VK not set");
                return false;
            }
        };
        let verifier = match UltraHonkVerifier::new(&env, &vk) {
            Ok(v) => v,
            Err(_) => {
                log!(&env, "VK parse failed");
                return false;
            }
        };
        if verifier.verify(&env, &proof, &public_inputs).is_err() {
            log!(&env, "Proof verification failed");
            return false;
        }

        // ---- DEFENSE-IN-DEPTH: cross-check public inputs match arguments ----
        // The circuit's public input schema (threshold, att_type, timestamp,
        // commitment) is public. We re-check the threshold + timestamp fields
        // match what the caller claimed, to prevent an honest proof being
        // mislabeled.
        let min_threshold = read_field_u64(&public_inputs, 0);
        let att_type_pi = read_field_u64(&public_inputs, 32);
        let timestamp_pi = read_field_u64(&public_inputs, 64);

        if min_threshold != threshold as u64 {
            log!(&env, "public input threshold mismatch");
            return false;
        }
        if att_type_pi != attestation_type_to_u64(&attestation_type) {
            log!(&env, "public input att_type mismatch");
            return false;
        }
        if timestamp_pi <= 1_704_067_200 {
            // before Jan 1 2024 — circuit would have rejected, but be explicit
            log!(&env, "timestamp too old");
            return false;
        }

        // ---- ISSUE ATTESTATION ----
        let now = env.ledger().timestamp();
        let expiry = now + 7_776_000; // 90 days in seconds

        // For the audit hash we hash (public_inputs || proof) so a single
        // attestation cannot be replayed with a different proof later.
        let mut audit = Bytes::new(&env);
        audit.append(&public_inputs);
        audit.append(&proof);
        let proof_hash = env.crypto().sha256(&audit);

        let attestation = Attestation {
            holder: user.clone(),
            attestation_type: attestation_type.clone(),
            threshold,
            issued_at: now,
            expires_at: expiry,
            proof_hash: proof_hash.into(),
        };

        // Store the attestation
        let key = AttestationKey {
            holder: user.clone(),
            att_type: attestation_type.clone(),
        };
        env.storage().persistent().set(&key, &attestation);

        // Bump storage TTL to match expiry (90 days)
        env.storage().persistent().extend_ttl(&key, 1_555_200, 1_555_200);

        // Increment total attestations counter
        let total: u64 = env
            .storage()
            .instance()
            .get(&DataKey::TotalAttestations)
            .unwrap_or(0);
        env.storage()
            .instance()
            .set(&DataKey::TotalAttestations, &(total + 1));

        log!(&env, "Attestation issued for user");

        true
    }

    // --------------------------------------------------------
    // QUERY: Check if an address has a valid attestation
    // --------------------------------------------------------

    /// Check if an address holds a valid (non-expired) attestation.
    pub fn check(env: Env, address: Address, attestation_type: Symbol) -> bool {
        let key = AttestationKey {
            holder: address,
            att_type: attestation_type,
        };

        match env
            .storage()
            .persistent()
            .get::<AttestationKey, Attestation>(&key)
        {
            Some(att) => {
                let now = env.ledger().timestamp();
                att.expires_at > now
            }
            None => false,
        }
    }

    /// Get full attestation details
    pub fn get_attestation(
        env: Env,
        address: Address,
        attestation_type: Symbol,
    ) -> Option<Attestation> {
        let key = AttestationKey {
            holder: address,
            att_type: attestation_type,
        };
        env.storage().persistent().get(&key)
    }

    // --------------------------------------------------------
    // USER: Revoke own attestation
    // --------------------------------------------------------

    /// User can revoke their own attestation at any time
    pub fn revoke(env: Env, user: Address, attestation_type: Symbol) {
        user.require_auth();

        let key = AttestationKey {
            holder: user,
            att_type: attestation_type,
        };
        env.storage().persistent().remove(&key);
        log!(&env, "Attestation revoked");
    }

    // --------------------------------------------------------
    // STATS
    // --------------------------------------------------------

    /// Get total number of attestations ever issued
    pub fn total_attestations(env: Env) -> u64 {
        env.storage()
            .instance()
            .get(&DataKey::TotalAttestations)
            .unwrap_or(0)
    }
}

// ============================================================
// Internal helpers
// ============================================================

fn read_field_u64(bytes: &Bytes, offset: u32) -> u64 {
    let mut field = [0u8; 32];
    bytes
        .slice(offset..offset + 32)
        .copy_into_slice(&mut field);
    let mut value = [0u8; 8];
    value.copy_from_slice(&field[24..32]);
    u64::from_be_bytes(value)
}

fn attestation_type_to_u64(t: &Symbol) -> u64 {
    if *t == symbol_short!("income") {
        1
    } else if *t == symbol_short!("balance") {
        2
    } else if *t == symbol_short!("credit") {
        3
    } else {
        0
    }
}

// ============================================================
// Tests
// ============================================================

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::{testutils::Address as _, Bytes, Env};

    fn make_valid_vk(env: &Env) -> Bytes {
        Bytes::from_slice(env, include_bytes!("../testdata/valid_vk.bin"))
    }

    fn make_invalid_vk(env: &Env) -> Bytes {
        let mut vk = Bytes::new(env);
        for _ in 0..55 {
            vk.extend_from_slice(&[0u8; 32]);
        }
        vk
    }

    fn make_client<'a>(env: &'a Env) -> (ZkProofVerifierClient<'a>, Address) {
        let admin = Address::generate(env);
        let vk = make_valid_vk(env);
        // Register invokes the constructor with the provided args.
        let contract_id = env.register(ZkProofVerifier, (admin.clone(), vk));
        let client = ZkProofVerifierClient::new(env, &contract_id);
        (client, admin)
    }

    #[test]
    fn test_no_attestation_returns_false() {
        let env = Env::default();
        let (client, _admin) = make_client(&env);

        let user = Address::generate(&env);
        let att_type = symbol_short!("income");

        // No attestations exist yet
        assert!(!client.check(&user, &att_type));
        assert!(client.get_attestation(&user, &att_type).is_none());
    }

    #[test]
    fn test_total_attestations_starts_at_zero() {
        let env = Env::default();
        let (client, _admin) = make_client(&env);
        assert_eq!(client.total_attestations(), 0);
    }

    #[test]
    fn test_verification_key_storage_roundtrip() {
        let env = Env::default();
        let (client, admin) = make_client(&env);

        // Overwrite the constructor VK with a fresh valid one.
        let new_vk = make_valid_vk(&env);
        env.mock_all_auths();
        client.store_verification_key(&admin, &new_vk);

        let stored = client.get_verification_key().unwrap();
        assert_eq!(stored.len(), new_vk.len());
    }

    #[test]
    #[should_panic(expected = "Invalid verification key")]
    fn test_constructor_rejects_invalid_verification_key() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let invalid_vk = make_invalid_vk(&env);
        let _ = env.register(ZkProofVerifier, (admin, invalid_vk));
    }
}
